server:
  port: 8080

spring:
  application:
    name: uocns-se
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/uocns_se}
    username: ${DATABASE_USER:postgres}
    password: ${DATABASE_PASSWORD:align}
  jpa:
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL9Dialect

generator:
  results:
    path: /var/uocns/
